// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmi-P1BsATeTcUju7PosilXijbvSJffsU',
    appId: '1:106364488558:web:f37f54d95c4a3eccf30f7f',
    messagingSenderId: '106364488558',
    projectId: 'agriexpert-e10c2',
    authDomain: 'agriexpert-e10c2.firebaseapp.com',
    storageBucket: 'agriexpert-e10c2.firebasestorage.app',
    measurementId: 'G-EWWY2NDWWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Mv5UI7sB-pKWM-TEVt76gKs5i1hfN2Y',
    appId: '1:106364488558:android:ad672063542e8642f30f7f',
    messagingSenderId: '106364488558',
    projectId: 'agriexpert-e10c2',
    storageBucket: 'agriexpert-e10c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07vEV0WOTEgHVaRCTxynyWchNlFCimSA',
    appId: '1:106364488558:ios:9d3a375488ef994ef30f7f',
    messagingSenderId: '106364488558',
    projectId: 'agriexpert-e10c2',
    storageBucket: 'agriexpert-e10c2.firebasestorage.app',
    iosBundleId: 'com.example.agriexpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB07vEV0WOTEgHVaRCTxynyWchNlFCimSA',
    appId: '1:106364488558:ios:9d3a375488ef994ef30f7f',
    messagingSenderId: '106364488558',
    projectId: 'agriexpert-e10c2',
    storageBucket: 'agriexpert-e10c2.firebasestorage.app',
    iosBundleId: 'com.example.agriexpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmi-P1BsATeTcUju7PosilXijbvSJffsU',
    appId: '1:106364488558:web:8f2e134e568e7852f30f7f',
    messagingSenderId: '106364488558',
    projectId: 'agriexpert-e10c2',
    authDomain: 'agriexpert-e10c2.firebaseapp.com',
    storageBucket: 'agriexpert-e10c2.firebasestorage.app',
    measurementId: 'G-G2ZN8PSHNR',
  );
}
